# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jano/prog/libnxtdc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jano/prog/libnxtdc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jano/prog/libnxtdc/CMakeFiles /home/jano/prog/libnxtdc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jano/prog/libnxtdc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nxtdc

# Build rule for target.
nxtdc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nxtdc
.PHONY : nxtdc

# fast build rule for target.
nxtdc/fast:
	$(MAKE) -f CMakeFiles/nxtdc.dir/build.make CMakeFiles/nxtdc.dir/build
.PHONY : nxtdc/fast

#=============================================================================
# Target rules for targets named test_lib

# Build rule for target.
test_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lib
.PHONY : test_lib

# fast build rule for target.
test_lib/fast:
	$(MAKE) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/build
.PHONY : test_lib/fast

error.o: error.c.o
.PHONY : error.o

# target to build an object file
error.c.o:
	$(MAKE) -f CMakeFiles/nxtdc.dir/build.make CMakeFiles/nxtdc.dir/error.c.o
.PHONY : error.c.o

error.i: error.c.i
.PHONY : error.i

# target to preprocess a source file
error.c.i:
	$(MAKE) -f CMakeFiles/nxtdc.dir/build.make CMakeFiles/nxtdc.dir/error.c.i
.PHONY : error.c.i

error.s: error.c.s
.PHONY : error.s

# target to generate assembly for a file
error.c.s:
	$(MAKE) -f CMakeFiles/nxtdc.dir/build.make CMakeFiles/nxtdc.dir/error.c.s
.PHONY : error.c.s

lowlevel.o: lowlevel.c.o
.PHONY : lowlevel.o

# target to build an object file
lowlevel.c.o:
	$(MAKE) -f CMakeFiles/nxtdc.dir/build.make CMakeFiles/nxtdc.dir/lowlevel.c.o
.PHONY : lowlevel.c.o

lowlevel.i: lowlevel.c.i
.PHONY : lowlevel.i

# target to preprocess a source file
lowlevel.c.i:
	$(MAKE) -f CMakeFiles/nxtdc.dir/build.make CMakeFiles/nxtdc.dir/lowlevel.c.i
.PHONY : lowlevel.c.i

lowlevel.s: lowlevel.c.s
.PHONY : lowlevel.s

# target to generate assembly for a file
lowlevel.c.s:
	$(MAKE) -f CMakeFiles/nxtdc.dir/build.make CMakeFiles/nxtdc.dir/lowlevel.c.s
.PHONY : lowlevel.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/test_lib.dir/build.make CMakeFiles/test_lib.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... nxtdc"
	@echo "... rebuild_cache"
	@echo "... test_lib"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... lowlevel.o"
	@echo "... lowlevel.i"
	@echo "... lowlevel.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

